sonar.projectKey=hadi-94_convo-hub-api
sonar.organization=hadi-94

# Scan only application source
sonar.sources=.

# Exclude generated and third-party content
sonar.exclusions=\
node_modules/**,\
vendor/**,\
coverage/**,\
devsec-analysis/**,\
tests/**

# JavaScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info
